brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 宿主机访问必须写宿主机地址，不能留容器内网 IP
brokerIP1 = 127.0.0.1
namesrvAddr = rmqnamesrv:9876
autoCreateTopicEnable = true
listenPort = 10911
